name: Upload Python Package

on:
  push:
    paths: 
      - 'efb_patch_middleware/__version__.py'
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        isbeta=`cat ./efb_patch_middleware/__version__.py | grep 'version' | grep -E 'a|b' | wc -l`
        if [ $isbeta -gt 0 ]; then twine upload --repository-url https://test.pypi.org/legacy/ dist/*; else twine upload dist/*; fi
